[project]
name = "fastapi_with_docker_uv_dev"
version = "0.1.0"
description = "Una aplicación FastAPI simple con uv para desarrollo ejecutándose en Docker"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.116.0,<0.117.0"
]
